# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=70)),
                ('time', models.CharField(max_length=17)),
                ('place', models.CharField(max_length=17)),
                ('description', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=17)),
                ('_type', models.CharField(max_length=17)),
                ('school', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(verbose_name='start')),
                ('endTime', models.DateTimeField(verbose_name='end')),
                ('_type', models.CharField(max_length=17)),
                ('state', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='SignupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=17)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.MyUser'),
        ),
    ]
