# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=17),
            preserve_default=False,
        ),
    ]
