# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_course_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='credit_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='credit_limit',
            field=models.IntegerField(default=0),
        ),
    ]
