# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170514_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='standard',
            field=models.CharField(default='', max_length=77),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.CharField(default='', max_length=77),
        ),
    ]
