# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_course_mytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupinfo',
            name='gpa',
            field=models.FloatField(default=4.0),
        ),
    ]
